services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "7080:7080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
